spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:mysql://localhost:3306/mywallet?ApplicationName=mywallet-dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: true

---

brapiFindTicket: "https://brapi.dev/api/quote"
