
#spring:
#  profiles:
#    include:
#      - springdoc
---
app:
  version: 1.0.0
  title: My Wallet
  paths:
    v1: /v1
---
spring:
  application:
    name: mywallet_api
  flyway:
    enabled: true
    baseline-on-migrate: true
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 4
      minimum-idle: 2
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: false
    hibernate.ddl-auto: validate
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
server:
  port: 8080
  servlet:
    context-path: /api